{
  "id": "LC-aws-codebuild-start-buildspec-override",
  "name": "AWS CodeBuild Buildspec Override Abuse",
  "provider": "aws",
  "service": "codebuild",
  "description": "Starting CodeBuild jobs with inline buildspec overrides to run arbitrary commands under CI trust context.",
  "attack_category": "cicd_abuse",
  "mitre_attack": [
    {
      "tactic": "Execution",
      "technique_id": "T1059",
      "technique_name": "Command and Scripting Interpreter"
    }
  ],
  "example": {
    "type": "cli",
    "command_or_request": "aws codebuild start-build --project-name release-pipeline --buildspec-override \"version:0.2\nphases:\n build:\n  commands:\n   - aws s3 cp s3://prod-data ./\""
  },
  "telemetry": {
    "required_logs": [
      "AWS control plane audit logs",
      "AWS identity/authentication logs"
    ],
    "minimum_config": [
      "Enable organization/subscription/project level audit logging",
      "Retain logs in immutable storage with centralized aggregation"
    ],
    "blind_spots": [
      "Actions from trusted automation identities may look benign",
      "Short-lived tokens can reduce actor attribution confidence"
    ],
    "retention_recommendation_days": 365
  },
  "detection": {
    "hypotheses": [
      "This action is uncommon for the principal or workload baseline",
      "The activity occurs outside approved change windows"
    ],
    "analytics": [
      "Alert on first-time use of API by principal in 30 days",
      "Correlate with subsequent permission changes or data transfer spikes"
    ],
    "false_positive_considerations": [
      "Legitimate incident response or break-glass operations",
      "Planned infrastructure migrations or deployment events"
    ]
  },
  "risk": {
    "privilege_required": 3,
    "ease_of_abuse": 4,
    "impact": 4,
    "detection_likelihood": 3,
    "evasion_potential": 3,
    "score": 7.0,
    "severity": "high"
  },
  "mitigation": [
    "Enforce least privilege and scoped role assignments",
    "Require approval workflows and alerting for sensitive API calls"
  ],
  "references": [
    "https://docs.aws.amazon.com/codebuild/latest/APIReference/API_StartBuild.html",
    "https://attack.mitre.org/techniques/T1059/"
  ],
  "status": "reviewed",
  "created_at": "2026-02-14T00:00:00Z",
  "updated_at": "2026-02-14T00:00:00Z"
}
